##Fundamentals of Pytorch

**Run over the google colab GPU**

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


**Importing the libraries**

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


**Scaler, Matrix , Tensor Formation**

In [ ]:
one_d = torch.tensor(1)
one_d

tensor(1)

In [ ]:
one_d.ndim

0

In [ ]:
two_d = torch.tensor([[1,2,3],
                     [4,5,6]])

In [ ]:
two_d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
two_d.ndim

2

In [ ]:
two_d.shape

torch.Size([2, 3])

In [ ]:
three_d = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]],
                        [[11,12,13],
                         [14,15,15],
                         [17,18,19]]])

In [ ]:
three_d.shape

torch.Size([2, 3, 3])

**Random Matrix Formation**

In [ ]:
rand_matrix = torch.rand(size=(4,4))
rand_matrix

tensor([[0.7708, 0.9792, 0.9605, 0.8715],
        [0.7775, 0.8423, 0.1987, 0.4656],
        [0.5599, 0.8395, 0.5117, 0.4142],
        [0.1312, 0.8924, 0.5925, 0.9586]])

In [ ]:
rand_matrix.dtype

torch.float32

**zeros and ones matrix**

In [ ]:
zero_matrix = torch.zeros(size=(2,3))
zero_matrix

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
one_matrix = torch.ones(size=(2,3))
one_matrix

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
one_matrix.ndim

2

**arange function**

In [ ]:
random_matrix = torch.arange(start=0,end=10,step=2)
random_matrix

tensor([0, 2, 4, 6, 8])

In [ ]:
random_matrix.ndim

1

In [ ]:
random_matrix.shape

torch.Size([5])

**torch datatype**

In [ ]:
random_data_type = torch.rand(3,4)
random_data_type.ndim,random_data_type.shape,random_data_type.dtype,random_data_type.device

(2, torch.Size([3, 4]), torch.float32, device(type='cpu'))

**Mathematical Calculations**

In [ ]:
tensor = torch.tensor([1,2,3])
tensor.ndim,tensor.shape,tensor.dtype

(1, torch.Size([3]), torch.int64)

In [ ]:
tensor + 5

tensor([6, 7, 8])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [ ]:
tensor*tensor

tensor([1, 4, 9])

**Matrix Multiplication**

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
mat1 = torch.tensor([[1,2,3],
                    [4,5,6],
                    [7,8,9]], dtype=torch.float32)
mat2 = torch.tensor([[1,2,3],
                    [4,5,6],
                    [7,8,9]], dtype=torch.float32)

In [ ]:
torch.matmul(mat1,mat2.T)

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])

**max, min, mean, sum, argmax, argmin**

In [ ]:
num = torch.arange(0,100,10)
num

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
num.max()

tensor(90)

In [ ]:
num.argmax()

tensor(9)

In [ ]:
num.min() , num.argmin()

(tensor(0), tensor(0))

In [ ]:
num.sum()

tensor(450)

In [ ]:
num.type(torch.float32).sum()

tensor(450.)

**Reshaping , Viewing, Stacking, Squeezing, Unsqueezing**

In [ ]:
num.shape

torch.Size([10])

In [ ]:
num.reshape(1,10)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
num.squeeze()

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
num.unsqueeze(dim=0)

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
num

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
num_temp = num.view(1,10)
num_temp

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
num_temp[:,0]=1

In [ ]:
num_temp,num

(tensor([[ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [ ]:
num_stack = torch.stack([num,num,num],dim=-2)
num_stack

tensor([[ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 1, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

**Indexing**

In [ ]:
matrix = torch.arange(0,100,10).reshape(1,5,2)

In [ ]:
matrix

tensor([[[ 0, 10],
         [20, 30],
         [40, 50],
         [60, 70],
         [80, 90]]])

In [ ]:
matrix[0]

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [ ]:
matrix[0][0]

tensor([ 0, 10])

In [ ]:
matrix[0][0][0]

tensor(0)

In [ ]:
matrix[:,0,0]

tensor([0])

**Pytorch and Numpy**

In [ ]:
num_arr = np.arange(1.0,10.0)
num_arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
tensor_arr = torch.from_numpy(num_arr)
tensor_arr

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [ ]:
tensor_arr.type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
tensor_arr.dtype

torch.float64

In [ ]:
# to convert back to numpy from tensor
tensor_ones = torch.ones(10)
tensor_numpy = tensor_ones.numpy()
tensor_ones,tensor_numpy

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Seed**

In [ ]:
torch.manual_seed(42)
rand1 = torch.rand(3,4)
rand2 = torch.rand(3,4)

rand1,rand2

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]))

In [ ]:
rand1==rand2    #single assigning of seed will not have equal random_variables

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
#assigning different seed to different variables
torch.manual_seed(42)
rand1 = torch.rand(3,4)

torch.manual_seed(42)
rand2 = torch.rand(3,4)

rand1,rand2

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [ ]:
rand1==rand2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

**Accessing GPU**

In [ ]:
#Using google colab follow the steps to change runtime to GPU:
'''
Clikc on runtime -> Change the runtime -> click free GPU access -> save
'''

In [ ]:
!nvidia-smi

Mon Mar 31 08:04:39 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   54C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
import numpy as np

In [ ]:
is_available = "cuda" if torch.cuda.is_available() else "cpu"
is_available

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.rand(3,4)
tensor_gpu = tensor.to(is_available)
tensor_gpu

tensor([[0.0343, 0.2532, 0.8260, 0.4588],
        [0.7275, 0.9499, 0.3487, 0.1988],
        [0.3959, 0.8481, 0.4836, 0.9127]], device='cuda:0')

In [ ]:
tensor_gpu.dtype

torch.float32

In [ ]:
nump_arr = np.arange(1.0,9.0)
nump_arr

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
tensor_numpy = torch.from_numpy(nump_arr)
tensor_numpy

tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [ ]:
tensor_numpy_gpu = tensor_numpy.to(is_available)
tensor_numpy_gpu

tensor([1., 2., 3., 4., 5., 6., 7., 8.], device='cuda:0', dtype=torch.float64)

In [ ]:
# tensor_numpy_gpu.numpy() -> cannot convert to numpy again on gpu